---
# tasks file for :device_credential
# From file: device_credential.py
- name: update_device_credentials

  cisco.dnac.device_credential:
    state: update  # required
    settings:  # required
      cliCredential:
        description: SomeValue  # string
        username: SomeValue  # string
        password: SomeValue  # string
        enablePassword: SomeValue  # string
        id: SomeValue  # string
      snmpV2cRead:
        description: SomeValue  # string
        readCommunity: SomeValue  # string
        id: SomeValue  # string
      snmpV2cWrite:
        description: SomeValue  # string
        writeCommunity: SomeValue  # string
        id: SomeValue  # string
      snmpV3:
        authPassword: SomeValue  # string
        authType: SomeValue  # string
        snmpMode: SomeValue  # string
        privacyPassword: SomeValue  # string
        privacyType: SomeValue  # string
        username: SomeValue  # string
        description: SomeValue  # string
        id: SomeValue  # string
      httpsRead:
        name: SomeValue  # string
        username: SomeValue  # string
        password: SomeValue  # string
        port: SomeValue  # string
        id: SomeValue  # string
      httpsWrite:
        name: SomeValue  # string
        username: SomeValue  # string
        password: SomeValue  # string
        port: SomeValue  # string
        id: SomeValue  # string
