---
# tasks file for :global_credential
# From file: global_credential.py
- name: update_global_credentials

  cisco.dnac.global_credential:
    state: update  # required
    global_credential_id: SomeValue  # string, required
    siteUuids:
    - SomeValue  # string
