---
# tasks file for :event_api_status
# From file: event_api_status.py
- name: get_status_api_for_events

  cisco.dnac.event_api_status:
    state: query  # required
    execution_id: SomeValue  # string, required
  register: nm_get_status_api_for_events
