---
# tasks file forinterface
# From file: interface.py
- name: get_ospf_interfaces

  cisco.dnac.interface:
    state: query  # required
    ospf: True  # boolean, required
  register: nm_get_ospf_interfaces
