---
# tasks file forios_user
# From file: ios_user.py
- name: create a new user

  cisco.ios.ios_user:
    name: ansible
    nopassword: true
    sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present
