---
# tasks file for :global_credential_http_read
# From file: global_credential_http_read.py
- name: update_http_read_credential

  cisco.dnac.global_credential_http_read:
    state: update  # required
    password: SomeValue  # string, required
    port: 1  #  integer, required
    username: SomeValue  # string, required
    comments: SomeValue  # string
    credentialType: # valid values are 'GLOBAL',
      # 'APP'.
      SomeValue  # string
    description: SomeValue  # string
    id: SomeValue  # string
    instanceTenantId: SomeValue  # string
    instanceUuid: SomeValue  # string
    secure: True  # boolean
