---
# tasks file for :discovery_network_device
# From file: discovery_network_device.py
- name: get_discovered_network_devices_by_discovery_id

  cisco.dnac.discovery_network_device:
    state: query  # required
    id: SomeValue  # string, required
    task_id: SomeValue  # string
  register: nm_get_discovered_network_devices_by_discovery_id
