---
# tasks file fordiscovery
# From file: discovery.py
- name: delete_discovery_by_specified_range

  cisco.dnac.discovery:
    state: delete  # required
    records_to_delete: 1  #  integer, required
    start_index: 1  #  integer, required
