---
# tasks file forissue_enrichment_details
# From file: issue_enrichment_details.py
- name: get_issue_enrichment_details

  cisco.dnac.issue_enrichment_details:
    state: query  # required
    headers:  # required
  register: nm_get_issue_enrichment_details
