---
# tasks file forinterface
# From file: interface.py
- name: get_interface_details

  cisco.dnac.interface:
    state: query  # required
    device_id: SomeValue  # string, required
    name: SomeValue  # string, required
  register: nm_get_interface_details
