---
# tasks file forglobal_credential_netconf
# From file: global_credential_netconf.py
- name: create_netconf_credentials

  cisco.dnac.global_credential_netconf:
    state: create  # required
    payload:  # required
    - netconfPort: SomeValue  # string, required
      comments: SomeValue  # string
      credentialType: SomeValue  # string
      description: SomeValue  # string
      id: SomeValue  # string
      instanceTenantId: SomeValue  # string
      instanceUuid: SomeValue  # string
