---
# tasks file forclient_health
# From file: client_health.py
- name: get_overall_client_health

  cisco.dnac.client_health:
    state: query  # required
    timestamp: 1  #  integer
  register: nm_get_overall_client_health
