---
# tasks file forsda_host_onboarding_access_point
# From file: sda_host_onboarding_access_point.py
- name: get_port_assignment_for_access_point

  cisco.dnac.sda_host_onboarding_access_point:
    state: query  # required
    device_ip: SomeValue  # string, required
    interface_name: SomeValue  # string, required
  register: nm_get_port_assignment_for_access_point
