---
# tasks file forios_lacp_interfaces
# From file: ios_lacp_interfaces.py
- name: Replaces device configuration of listed lacp_interfaces with provided configuration

  cisco.ios.ios_lacp_interfaces:
    config:
    - name: GigabitEthernet0/3
      port_priority: 40
    - name: Port-channel10
      fast_switchover: true
      max_bundle: 2
    state: replaced
