---
# tasks file fordiscovery
# From file: discovery.py
- name: start_discovery

  cisco.dnac.discovery:
    state: create  # required
    discoveryType: SomeValue  # string, required
    ipAddressList: SomeValue  # string, required
    name: SomeValue  # string, required
    snmpVersion: SomeValue  # string, required
    cdpLevel: 1  #  integer
    enablePasswordList:
    - SomeValue  # string
    globalCredentialIdList:
    - SomeValue  # string
    httpReadCredential:
      comments: SomeValue  # string
      credentialType: SomeValue  # string
      description: SomeValue  # string
      id: SomeValue  # string
      instanceTenantId: SomeValue  # string
      instanceUuid: SomeValue  # string
      password: SomeValue  # string
      port: 1  #  integer
      secure: True  # boolean
      username: SomeValue  # string
    httpWriteCredential:
      comments: SomeValue  # string
      credentialType: SomeValue  # string
      description: SomeValue  # string
      id: SomeValue  # string
      instanceTenantId: SomeValue  # string
      instanceUuid: SomeValue  # string
      password: SomeValue  # string
      port: 1  #  integer
      secure: True  # boolean
      username: SomeValue  # string
    ipFilterList:
    - SomeValue  # string
    lldpLevel: 1  #  integer
    netconfPort: SomeValue  # string
    noAddNewDevice: True  # boolean
    parentDiscoveryId: SomeValue  # string
    passwordList:
    - SomeValue  # string
    preferredMgmtIPMethod: SomeValue  # string
    protocolOrder: SomeValue  # string
    reDiscovery: True  # boolean
    retry: 1  #  integer
    snmpAuthPassphrase: SomeValue  # string
    snmpAuthProtocol: SomeValue  # string
    snmpMode: SomeValue  # string
    snmpPrivPassphrase: SomeValue  # string
    snmpPrivProtocol: SomeValue  # string
    snmpROCommunity: SomeValue  # string
    snmpROCommunityDesc: SomeValue  # string
    snmpRWCommunity: SomeValue  # string
    snmpRWCommunityDesc: SomeValue  # string
    snmpUserName: SomeValue  # string
    timeout: 1  #  integer
    updateMgmtIp: True  # boolean
    userNameList:
    - SomeValue  # string
