---
# tasks file for :network_device_config
# From file: network_device_config.py
- name: get_device_config_count

  cisco.dnac.network_device_config:
    state: query  # required
    count: True  # boolean, required
  register: nm_get_device_config_count
