---
# tasks file forios_lag_interfaces
# From file: ios_lag_interfaces.py
- name: Gather listed LAG interfaces with provided configurations

  cisco.ios.ios_lag_interfaces:
    config:
    state: gathered
