---
# tasks file for :ios_vrf
# From file: ios_vrf.py
- name: configure a vrf named management

  cisco.ios.ios_vrf:
    name: management
    description: oob mgmt vrf
    interfaces:
    - Management1
