---
# tasks file forfile
# From file: file.py
- name: download_a_file_by_fileid

  cisco.dnac.file:
    state: query  # required
    file_id: SomeValue  # string, required
    dirpath: SomeValue  # string
    save_file: True  # boolean
  register: nm_download_a_file_by_fileid
