---
# tasks file for :network_device_wireless_info
# From file: network_device_wireless_info.py
- name: get_wireless_lan_controller_details_by_id

  cisco.dnac.network_device_wireless_info:
    state: query  # required
    id: SomeValue  # string, required
  register: nm_get_wireless_lan_controller_details_by_id
