---
# tasks file for :sda_border_device
# From file: sda_border_device.py
- name: deletes_border_device

  cisco.dnac.sda_border_device:
    state: delete  # required
    device_ipaddress: SomeValue  # string, required
