---
# tasks file for :sda_control_plane_device
# From file: sda_control_plane_device.py
- name: get_control_plane_device

  cisco.dnac.sda_control_plane_device:
    state: query  # required
    device_ipaddress: SomeValue  # string, required
  register: nm_get_control_plane_device
