---
# tasks file forsda_control_plane_device
# From file: sda_control_plane_device.py
- name: add_control_plane_device

  cisco.dnac.sda_control_plane_device:
    state: create  # required
    payload:  # required
    - deviceManagementIpAddress: SomeValue  # string
      siteNameHierarchy: SomeValue  # string
