---
# tasks file for :ios_lacp
# From file: ios_lacp.py
- name: Merge provided configuration with device configuration

  cisco.ios.ios_lacp:
    config:
      system:
        priority: 123
    state: merged
